
name: Build and Deploy

on:
  push:
    branches:
      - devtest

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image

      run:  docker build -t calc-and-base:latest . --no-cache

    - name: Stop and remove existing container
      run: |
       CONTAINER_NAME=web_app  
        CONTAINER_ID=$(docker ps -q --filter "name=$CONTAINER_NAME")
        if [ ! -z "$CONTAINER_ID" ]; then
           docker stop $CONTAINER_ID
           docker rm $CONTAINER_ID
        fi

    - name: Run Docker container
      run:  docker run --name web_app -p 3000:3000 -d calc-and-base:latest

