name: deploy-on-constrdase

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup certificate and key
      run: |
        echo "${{ secrets.CERTIFICATE_B64 }}" | base64 --decode > certificate.crt
        echo "${{ secrets.PRIVATE_KEY_B64 }}" | base64 --decode > private.key

    - name: Stop container
      run: make del

    - name: Build
      run: make build

    - name: Run container
      run: make run
